import { HIT } from "../data/dice-data"
import { PREMADE_ATTACKS } from "../data/attack-data"

describe("Attack", () => {
    it("works with basic weapons against black die", () => {
        expect(PREMADE_ATTACKS["A-12 Sniper Rifle"].calcaverage(['black'])[HIT]).toBeCloseTo(3.89)
        expect(PREMADE_ATTACKS["A280"].calcaverage(['black'])[HIT]).toBeCloseTo(2.39)
        expect(PREMADE_ATTACKS["All-Weather Rifle"].calcaverage(['black'])[HIT]).toBeCloseTo(1.60)
        expect(PREMADE_ATTACKS["Armored Gauntlets"].calcaverage(['black'])[HIT]).toBeCloseTo(2.54)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax"].calcaverage(['black'])[HIT]).toBeCloseTo(2.50)
        expect(PREMADE_ATTACKS["Bo-rifle"].calcaverage(['black'])[HIT]).toBeCloseTo(3.56)
        expect(PREMADE_ATTACKS["DC-15S Blaster"].calcaverage(['black'])[HIT]).toBeCloseTo(1.33)
        expect(PREMADE_ATTACKS["DDC Defender"].calcaverage(['black'])[HIT]).toBeCloseTo(1.50)
        expect(PREMADE_ATTACKS["DH-17"].calcaverage(['black'])[HIT]).toBeCloseTo(2.13)
        expect(PREMADE_ATTACKS["DL-44"].calcaverage(['black'])[HIT]).toBeCloseTo(2.20)
        expect(PREMADE_ATTACKS["DLT-19"].calcaverage(['black'])[HIT]).toBeCloseTo(3.16)
        expect(PREMADE_ATTACKS["DXR-6"].calcaverage(['black'])[HIT]).toBeCloseTo(3.39)
        expect(PREMADE_ATTACKS["Hunter's Rifle"].calcaverage(['black'])[HIT]).toBeCloseTo(2.42)
        expect(PREMADE_ATTACKS["Plasteel Staff"].calcaverage(['black'])[HIT]).toBeCloseTo(1.50)
        expect(PREMADE_ATTACKS["Polearm"].calcaverage(['black'])[HIT]).toBeCloseTo(3.09)
        expect(PREMADE_ATTACKS["Shu Yen's Lightsaber"].calcaverage(['black'])[HIT]).toBeCloseTo(2.56)
        expect(PREMADE_ATTACKS["Vibro Knucklers"].calcaverage(['black'])[HIT]).toBeCloseTo(2.75)
        expect(PREMADE_ATTACKS["Vibrosword"].calcaverage(['black'])[HIT]).toBeCloseTo(2.17)
        expect(PREMADE_ATTACKS["Sporting Blaster"].calcaverage(['black'])[HIT]).toBeCloseTo(3.23)
    })
    it("works with basic weapons against white die", () => {
        expect(PREMADE_ATTACKS["A-12 Sniper Rifle"].calcaverage(['white'])[HIT]).toBeCloseTo(3.90)
        expect(PREMADE_ATTACKS["A280"].calcaverage(['white'])[HIT]).toBeCloseTo(2.22)
        expect(PREMADE_ATTACKS["All-Weather Rifle"].calcaverage(['white'])[HIT]).toBeCloseTo(1.75)
        expect(PREMADE_ATTACKS["Armored Gauntlets"].calcaverage(['white'])[HIT]).toBeCloseTo(2.38)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax"].calcaverage(['white'])[HIT]).toBeCloseTo(2.65)
        expect(PREMADE_ATTACKS["Bo-rifle"].calcaverage(['white'])[HIT]).toBeCloseTo(3.55)
        expect(PREMADE_ATTACKS["DC-15S Blaster"].calcaverage(['white'])[HIT]).toBeCloseTo(1.74)
        expect(PREMADE_ATTACKS["DDC Defender"].calcaverage(['white'])[HIT]).toBeCloseTo(1.79)
        expect(PREMADE_ATTACKS["DH-17"].calcaverage(['white'])[HIT]).toBeCloseTo(2.07)
        expect(PREMADE_ATTACKS["DL-44"].calcaverage(['white'])[HIT]).toBeCloseTo(2.16)
        expect(PREMADE_ATTACKS["DLT-19"].calcaverage(['white'])[HIT]).toBeCloseTo(3.12)
        expect(PREMADE_ATTACKS["DXR-6"].calcaverage(['white'])[HIT]).toBeCloseTo(3.35)
        expect(PREMADE_ATTACKS["Hunter's Rifle"].calcaverage(['white'])[HIT]).toBeCloseTo(2.14)
        expect(PREMADE_ATTACKS["Plasteel Staff"].calcaverage(['white'])[HIT]).toBeCloseTo(1.79)
        expect(PREMADE_ATTACKS["Polearm"].calcaverage(['white'])[HIT]).toBeCloseTo(3.17)
        expect(PREMADE_ATTACKS["Shu Yen's Lightsaber"].calcaverage(['white'])[HIT]).toBeCloseTo(2.46)
        expect(PREMADE_ATTACKS["Sporting Blaster"].calcaverage(['white'])[HIT]).toBeCloseTo(2.72)
        expect(PREMADE_ATTACKS["Vibro Knucklers"].calcaverage(['white'])[HIT]).toBeCloseTo(2.38)
        expect(PREMADE_ATTACKS["Vibrosword"].calcaverage(['white'])[HIT]).toBeCloseTo(2.19)
    })
    it("works with surge with black die", () => {
        expect(PREMADE_ATTACKS["A-12 Sniper Rifle"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.75)
        expect(PREMADE_ATTACKS["A280"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.78)
        expect(PREMADE_ATTACKS["All-Weather Rifle"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(1.88)
        expect(PREMADE_ATTACKS["Armored Gauntlets"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.31)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.94)
        expect(PREMADE_ATTACKS["Bo-rifle"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.94)
        expect(PREMADE_ATTACKS["DDC Defender"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(1.71)
        expect(PREMADE_ATTACKS["DH-17"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.48)
        expect(PREMADE_ATTACKS["DXR-6"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.01)
        expect(PREMADE_ATTACKS["Hunter's Rifle"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.25)
        expect(PREMADE_ATTACKS["Plasteel Staff"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(1.71)
        expect(PREMADE_ATTACKS["Polearm"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.67)
        expect(PREMADE_ATTACKS["Shu Yen's Lightsaber"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.78)
        expect(PREMADE_ATTACKS["Sporting Blaster"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.59)
        expect(PREMADE_ATTACKS["Vibro Knucklers"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.72)
        expect(PREMADE_ATTACKS["Vibrosword"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.89)
    })
    it("works with surge with white die", () => {
        expect(PREMADE_ATTACKS["A-12 Sniper Rifle"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.77)
        expect(PREMADE_ATTACKS["A280"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.08)
        expect(PREMADE_ATTACKS["All-Weather Rifle"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(1.97)
        expect(PREMADE_ATTACKS["Armored Gauntlets"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.08)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.04)
        expect(PREMADE_ATTACKS["Bo-rifle"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.90)
        expect(PREMADE_ATTACKS["DDC Defender"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.06)
        expect(PREMADE_ATTACKS["DH-17"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.50)
        expect(PREMADE_ATTACKS["DXR-6"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.14)
        expect(PREMADE_ATTACKS["Hunter's Rifle"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.64)
        expect(PREMADE_ATTACKS["Plasteel Staff"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.06)
        expect(PREMADE_ATTACKS["Polearm"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.38)
        expect(PREMADE_ATTACKS["Shu Yen's Lightsaber"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.93)
        expect(PREMADE_ATTACKS["Sporting Blaster"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.03)
        expect(PREMADE_ATTACKS["Vibro Knucklers"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.08)
        expect(PREMADE_ATTACKS["Vibrosword"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.92)
    })
    it("works with mods with black die", () => {
        expect(PREMADE_ATTACKS["A280 with Coordinated Attack (BGR)"].calcaverage(['black'])[HIT]).toBeCloseTo(5.79)
        expect(PREMADE_ATTACKS["A280 with Disruption Cell and Coordinated Attack (RGR)"].calcaverage(['black'])[HIT]).toBeCloseTo(6.53)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax with High-Impact Guard"].calcaverage(['black'])[HIT]).toBeCloseTo(3.07)
        expect(PREMADE_ATTACKS["DH-17 with Disruption Cell and Point Blank Shot"].calcaverage(['black'])[HIT]).toBeCloseTo(4.08)
        expect(PREMADE_ATTACKS["Heirloom Dagger with Falling Leaf"].calcaverage(['black'])[HIT]).toBeCloseTo(3.01)
        expect(PREMADE_ATTACKS["Shrouded Lightsaber with High-Impact Guard, Falling Leaf, and Hidden"].calcaverage(['black'])[HIT]).toBeCloseTo(5.43)
    })
    it("works with mods with white dice", () => {
        expect(PREMADE_ATTACKS["A280 with Coordinated Attack (BGR)"].calcaverage(['white'])[HIT]).toBeCloseTo(5.00)
        expect(PREMADE_ATTACKS["A280 with Disruption Cell and Coordinated Attack (RGR)"].calcaverage(['white'])[HIT]).toBeCloseTo(5.69)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax with High-Impact Guard"].calcaverage(['white'])[HIT]).toBeCloseTo(2.92)
        expect(PREMADE_ATTACKS["DH-17 with Disruption Cell and Point Blank Shot"].calcaverage(['white'])[HIT]).toBeCloseTo(3.73)
        expect(PREMADE_ATTACKS["Heirloom Dagger with Falling Leaf"].calcaverage(['white'])[HIT]).toBeCloseTo(2.92)
        expect(PREMADE_ATTACKS["Shrouded Lightsaber with High-Impact Guard, Falling Leaf, and Hidden"].calcaverage(['white'])[HIT]).toBeCloseTo(4.44)
    })
    it("works with mods and surge with black die", () => {
        expect(PREMADE_ATTACKS["A280 with Coordinated Attack (BGR)"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(7.04)
        expect(PREMADE_ATTACKS["A280 with Disruption Cell and Coordinated Attack (RGR)"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(7.92)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax with High-Impact Guard"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.36)
        expect(PREMADE_ATTACKS["DH-17 with Disruption Cell and Point Blank Shot"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.05)
        expect(PREMADE_ATTACKS["Heirloom Dagger with Falling Leaf"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.28)
        expect(PREMADE_ATTACKS["Shrouded Lightsaber with High-Impact Guard, Falling Leaf, and Hidden"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(6.91)
    })
    it("works with mods and surge with white dice", () => {
        expect(PREMADE_ATTACKS["A280 with Coordinated Attack (BGR)"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.81)
        expect(PREMADE_ATTACKS["A280 with Disruption Cell and Coordinated Attack (RGR)"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(6.54)
        expect(PREMADE_ATTACKS["BD-1 Vibro-Ax with High-Impact Guard"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.90)
        expect(PREMADE_ATTACKS["DH-17 with Disruption Cell and Point Blank Shot"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.10)
        expect(PREMADE_ATTACKS["Heirloom Dagger with Falling Leaf"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.20)
        expect(PREMADE_ATTACKS["Shrouded Lightsaber with High-Impact Guard, Falling Leaf, and Hidden"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.59)
    })
    it("works with focused with black die", () => {
        expect(PREMADE_ATTACKS["Modified Blaster with Plasma Cell and Focused"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.00)
        expect(PREMADE_ATTACKS["Longblaster with Focused"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.78)
        expect(PREMADE_ATTACKS["Plasteel Staff with High-Impact Guard and Focused"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.84)
    })
    it("works with focused with white dice", () => {
        expect(PREMADE_ATTACKS["Modified Blaster with Plasma Cell and Focused"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.33)
        expect(PREMADE_ATTACKS["Longblaster with Focused"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(3.52)
        expect(PREMADE_ATTACKS["Plasteel Staff with High-Impact Guard and Focused"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.62)
    })
    it("works with rerolls with black die", () => {
        expect(PREMADE_ATTACKS["A280 with Disruption Cell and reroll"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.89)
        expect(PREMADE_ATTACKS["Close and Personal with Crushing Blow, Vibrobayonet, and reroll"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.56)
        expect(PREMADE_ATTACKS["Deathhammer with reroll"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.05)
        expect(PREMADE_ATTACKS["Repeating Blaster with reroll"].calcaverage(['black'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.19)
    })
    it("works with rerolls with white dice", () => {
        expect(PREMADE_ATTACKS["A280 with Disruption Cell and reroll"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.65)
        expect(PREMADE_ATTACKS["Close and Personal with Crushing Blow, Vibrobayonet, and reroll"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(5.76)
        expect(PREMADE_ATTACKS["Deathhammer with reroll"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(4.55)
        expect(PREMADE_ATTACKS["Repeating Blaster with reroll"].calcaverage(['white'], [0,0,1,0,0,0])[HIT]).toBeCloseTo(2.95)
    })
})